version: 0.0
os: linux
files:
  - source: ./tracker/
    destination: /usr/share/nginx/html/
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: ./clean.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./post_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./start_nginx.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./stop_nginx.sh
      timeout: 300
      runas: root
